on: [push]

jobs:
  job:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env
      - name: Event data
        run: cat $GITHUB_EVENT_PATH
      - name: Check
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          which node
          node --version
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
          ls "$RUNNER_TOOL_CACHE/node"
          curl https://api.github.com/rate_limit -u "token:$TOKEN"
      - uses: panticmilos/setup-node@v3.1
        with:
          node-version: ^16.13.2
      - name: Check
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          which node
          node --version
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
          ls "$RUNNER_TOOL_CACHE/node"
          curl https://api.github.com/rate_limit -u "token:$TOKEN"
      - uses: panticmilos/setup-node@v3.1
        with:
          node-version: 17.8.0
      - name: Check
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          which node
          node --version
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
          ls "$RUNNER_TOOL_CACHE/node"
          curl https://api.github.com/rate_limit -u "token:$TOKEN"