on: 
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  node-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [current, latest, node]
    steps:
      - uses: panticmilos/setup-node@main
      - name: Setup Node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify node and npm
        run: __tests__/verify-node.sh "${{ matrix.node-version }}"
        shell: bash